apiVersion: v1
kind: Service
metadata:
  name: dagger
  namespace: default
  labels:
    app: dagger
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: main
    protocol: TCP
  selector:
    app: dagger
  sessionAffinity: "ClientIP"

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
  name: dagger
  labels:
    app: dagger
spec:
  rules:
  - host: www.dustysarcophagus.com
    http:
      paths:
      - backend:
          serviceName: dagger
          servicePort: 80
        path: /workflows
      - backend:
          serviceName: dagger
          servicePort: 80
        path: /jobs
      - backend:
          serviceName: dagger
          servicePort: 80
        path: /definitions
      - backend:
          serviceName: dagger
          servicePort: 80
        path: /job_edges
      - backend:
          serviceName: dagger
          servicePort: 80
        path: /roots
      - backend:
          serviceName: dagger
          servicePort: 80
        path: /login
      - backend:
          serviceName: dagger
          servicePort: 80
        path: /logout
      - backend:
          serviceName: dagger
          servicePort: 80
        path: /sidekiq/dagger
      - backend:
          serviceName: dagger
          servicePort: 80
        path: /results/admin
      - backend:
          serviceName: dagger
          servicePort: 80
        path: /
  tls:
  - hosts:
    - www.dustysarcophagus.com
    secretName: ssl-cert-secret
