apiVersion: v1
kind: PersistentVolume
metadata:
  name: pg-vol
  labels:
    name: pg-vol
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
  storageClassName: vm
  hostPath:
    path: /data/pgdata/

---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: pg-vol-claim
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: vm
  selector:
    matchLabels:
      name: pg-vol
---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: postgres
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 0
  template:
    metadata:
      labels:
        app: postgres
        cpu_usage: blue
    spec:
      containers:
      - name: postgres-cont
        image: postgres:9.5.6
#        resources:
#          requests:
#            cpu: 330m
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          value: ''
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: pgdata
          mountPath: /var/lib/postgresql/data/
      volumes:
      - name: pgdata
#        hostPath:
#          path: /data/pgdata
        persistentVolumeClaim:
          claimName: pg-vol-claim
      nodeSelector:
        cpu_usage: blue
