---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: users
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: users
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 50%
      maxSurge: 0
  template:
    metadata:
      labels:
        app: users
        cpu_usage: blue
    spec:
      containers:
      - name: users
        image: users:mine
        resources:
          requests:
            cpu: 200m
        command: 
        ports:
        - containerPort: 80
        readinessProbe:
          httpGet:
            path: "/healthcheck"
            port: 80
          initialDelaySeconds: 3
          timeoutSeconds: 5
        env:
        - name: APP_NAME
          value: users
        - name: DOMAIN
          value: 
        - name: DB_HOST
          value: postgres
        - name: DB_NAME
          value: users_local
        - name: DB_PASSWORD
          value: ''
        - name: DB_PORT
          value: '5432'
        - name: DB_USERNAME
          value: postgres
        - name: GITHUB_CLIENT_ID
          value: 
        - name: GITHUB_CLIENT_SECRET
          value: 
        - name: RACK_ENV
          value: local
        - name: SESSION_SECRET
          value: 
        - name: WARDEN_GITHUB_VERIFIER_SECRET
          value:
        - name: SHARED_FS_MOUNT_PATH
          value: "/srv"
        - name: SHARED_VOL_CLAIM
          value: nfs-vol-claim
        - name: ADMIN_TOKEN
          value:
      nodeSelector:
        cpu_usage: blue
