apiVersion: v1
kind: Service
metadata:
  name: users
  namespace: default
  labels:
    app: users
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: main
    protocol: TCP
  selector:
    app: users
  sessionAffinity: "ClientIP"

---

apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    ingress.kubernetes.io/ssl-redirect: "true"
  name: users
  labels:
    app: users
spec:
  rules:
  - host: www.dustysarcophagus.com
    http:
      paths:
      - backend:
          serviceName: users
          servicePort: 80
        path: /users
      - backend:
          serviceName: users
          servicePort: 80
        path: /tokens
  tls:
  - hosts:
    - www.dustysarcophagus.com
    secretName: ssl-cert-dusty
