apiVersion: v1
kind: Pod
metadata:
  labels:
    app: etcd-viewer-pod
  name: etcd-viewer-pod
  namespace: default
spec:
  containers:
  - name: etcd-viewer-pod
    image: nikfoundas/etcd-viewer
    ports:
    - containerPort: 8080
