source 'https://rubygems.org'

gem 'pg'
gem 'activerecord', '~> 7.0'
gem 'rake'
gem 'sinatra'
gem 'sinatra-activerecord', '~> 2.0'
gem 'sinatra-initializers'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sinatra-has_scope', require: 'sinatra/has_scope'
gem 'will_paginate'
gem "will_paginate-bootstrap"
gem 'haml'
gem 'dotenv'
gem 'unicorn'
gem 'rack-rewrite'
gem 'rack-healthcheck'
# gem 'sinatra_auth_github'
gem 'sinatra_auth_github', :git => 'git://github.com/tylernm14/sinatra_auth_github'


group :development, :test do
  gem 'pry'
  gem 'racksh'
end

group :test do
  gem 'simplecov'
  gem 'factory_girl', '~> 4.8'
  gem 'rack-test'
  gem 'rspec'
  gem 'webmock'
end
