---
:verbose: true
development:
  :concurrency: 2
toolbox:
  :concurrency: 2
local:
  :concurrency: 2
staging:
  :concurrency: 4
production:
  :concurrency: 8
:queues:
  - start_workflow
  - launch_jobs
  - job_done
  - delete_kube_job
