

  # Note: Any file referenced via a 'cache' entry needs to be 
  # uploaded via the drop zone when creating a new workflow.
  # For this example a 'banana_output.txt' file needs to be uploaded
  # for the dragonfruit job.

---
jobs:
- cmd: "/timer.py"
  args:
  - 30s
  name: apple
  image: timer:mine
  outputs:
  - save: true
    local: output.txt
  workdir_prefix: apple
- cmd: "/timer.py"
  args:
  - 30s
  name: cantaloupe
  image: timer:mine
  outputs:
  - save: true
    local: output.txt
  workdir_prefix: cantaloupe
- cmd: "/gather_cpu_time.py"
  args:
  - apple
  - banana
  - cantaloupe
  name: dragonfruit
  image: timer:mine
  inputs:
  - local: apple/output.txt
  - cache: banana_output.txt
    local: banana/output.txt
  - local: cantaloupe/output.txt
  outputs:
  - save: true
    local: total_cpu_time.txt
neighbors:
  apple:
  - cantaloupe
  cantaloupe:
  - dragonfruit
